---
- hosts: monitoring
  gather_facts: yes
  tasks:  
  #Install dependes
  - name: Install packages ubuntu
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes
    become: yes
    when: ansible_os_family == 'Debian'

 #Install docker from docker repo
  - name: Create keyrings folder ubuntu
    file:
      path: '/etc/apt/keyrings'
      state: directory
    become: yes
    when: ansible_os_family == 'Debian'

  - name: Add apt key ubuntu
    apt_key:
      url: 'https://download.docker.com/linux/ubuntu/gpg'
      state: present
    become: yes
    when: ansible_os_family == 'Debian'

  - name: Add source list ubuntu
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
    become: yes
    when: ansible_os_family == 'Debian'

  - name: Install docker ubuntu
    apt:
     pkg:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose-plugin
     update_cache: yes
    become: yes
    when: ansible_os_family == 'Debian'
  
  - name: Install docker-compose
    ignore_errors: true
    except: sudo docker-compose_install.sh

  - name: Download monitoring containers
    ignore_errors: true
    expect:
      command: sudo mkdir -p /opt/monitoring $$ cd /opt/monitoring
      command: git clone https://github.com/Sergeshchukin/monitoring
      command: docker-compose -d docker-compose.yaml
